
[general]
	isEnabled = true
	logMissingEntries = false

	[general.hotbar]
		alwaysShow = false
		enableHotbar = true
		mergeDuplicates = true
		renderOverlays = true
		showStacksize = false
		#Range: 1 ~ 27
		slotLimit = 3
		#Range: > -2147483648
		xOffset = 0
		#Range: > -2147483648
		yOffset = -22

	[general.itempickup]
		#Range: > 0
		displayTime = 3000
		itemPickupIsEnabled = true
		#Range: > 0
		itemLimit = 10
		#Range: 0 ~ 1
		priorityMode = 0

